FROM miveo/centos-php-fpm:7.2
WORKDIR "/application"

RUN curl -sSLO https://github.com/mailhog/mhsendmail/releases/download/v0.2.0/mhsendmail_linux_amd64 \
    && chmod +x mhsendmail_linux_amd64 \
    && mv mhsendmail_linux_amd64 /usr/local/bin/mhsendmail

CMD ["php-fpm", "-F"]

EXPOSE 9000